services:

  payments-api:
    build:
      context: .
      dockerfile: payments-api/Dockerfile
    container_name: payments-api
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:8081/actuator/health | grep -q UP"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 20s
    networks:
      - resilience

  orders-api:
    build:
      context: .
      dockerfile: orders-api/Dockerfile
    container_name: orders-api
    ports:
      - "8080:8080"
    environment:
      PAYMENTS_BASE_URL: http://payments-api:8081
    depends_on:
      payments-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:8080/actuator/health | grep -q UP"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 20s
    networks:
      - resilience

networks:
  resilience:
    driver: bridge
